using Il2Cpp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FS_LevelEditor
{
    public static class LE_CustomErrorPopups
    {
        public static void MultipleObjectsWithSameID()
        {
            string title = "LEVEL EDITOR ERROR";
            string description = "This error was generated by the Level Editor mod, DON'T REPORT IT to Haze Games!";
            string errorString = "Two or more objects have the same ID, please report to Javialon_qv in FS Discord server.";
            string stackTrace = "Please attach with your report the Latest.log file in the MelonLoader folder and your level file.";

            MenuController.GetInstance().ShowCodeErrorPopup(title, description, errorString, stackTrace);
        }

        public static void ObjectWithoutObjectType()
        {
            string title = "LEVEL EDITOR ERROR";
            string description = "This error was generated by the Level Editor mod, DON'T REPORT IT to Haze Games!";
            string errorString = "An object doesn't have an assigned object type, please report to Javialon_qv in FS Discord server.";
            string stackTrace = "Please attach with your report the Latest.log file in the MelonLoader folder and your level file.";

            MenuController.GetInstance().ShowCodeErrorPopup(title, description, errorString, stackTrace);
        }

        public static void NoPlayerSpawnObjectDetected()
        {
            string title = "LEVEL EDITOR ERROR";
            string description = "This error was generated by the Level Editor mod, DON'T REPORT IT to Haze Games!";
            string errorString = "You tried to play a level but the mod couldn't detect any player spawn objects in the level, please report to Javialon_qv in FS Discord server.";
            string stackTrace = "Please attach with your report the Latest.log file in the MelonLoader folder and your level file.";

            MenuController.GetInstance().ShowCodeErrorPopup(title, description, errorString, stackTrace);
        }
    }
}
